### ISSUE TITLE
Questions about the task

### ISSUE THREAD

**Issue by mouseratti** [envrm/docker-compose-template#1]
Hello. I'm from Luxoft.
Currently, you're pull a repo on build step.
Could you, please, update your code in this way: repository should be pulled by docker **container** in runtime, **not by image** in build-time.
Is it possible?

**Comment by envrm** [comment]
Hello.
I've done it. New code isn't too exquisite, but it works.

Building:
docker-compose up -d --build

Executing:
docker-compose up -d

**Comment by mouseratti** [comment]
Good. And why haven't you created a separated **init.sh** script?

**Comment by envrm** [comment]
Because I understood this task literally: Создать докер-**образ**, который загружает свой код (**dockerfile, docker-compose.yml**) с github. There aren't any other files.

Of course, it is possible to load init.sh script into container with **ADD init.sh**.

**Comment by mouseratti** [comment]
ok. Accepted. Thank you!
